# =======================
# Jekyll Configuration File (_config.yml)
# =======================
# This file controls the overall settings of your Jekyll site.
# Think of it like the "brain" of your website.
#
# - Change the "title" and "description" to personalize your site.
# - The "theme" decides how your site looks (layout, style, colors).
# - You can add your own sections (about, projects, education, etc.)
#   in separate files, but this config will link them together.
# - If you change anything here, restart/rebuild your site
#   so the changes show up.
#
# TIP: Do not remove keys unless you know what they do.
#      Just update values (the words after the :) to fit your site.
#
# Example: title: My Portfolio Site
#
# Copy this file into your project and edit values to make
# your own unique portfolio!
# =======================

theme: jekyll-theme-cayman # theme Name 
title: Bhumi Patel # your Name 
description: Cybersecurity Graduate Student | Cloud Security Enthusiast # A title for your quick intro and goals
baseurl: "/portfolio"   # your repo name
